./comparar.py /oracle/csv_generados/dwh/repgi/ContadorDB-dwh-repgi.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-repgi.out 2>&1
./comparar.py /oracle/csv_generados/dwh/dbadmin/ContadorDB-dwh-dbadmin.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-dbadmin.out 2>&1
./comparar.py /oracle/csv_generados/dwh/reportes/ContadorDB-dwh-reportes.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-reportes.out 2>&1
./comparar.py /oracle/csv_generados/dwh/edata/ContadorDB-dwh-edata.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-edata.out 2>&1
./comparar.py /oracle/csv_generados/dwh/widget/ContadorDB-dwh-widget.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-widget.out 2>&1
./comparar.py /oracle/csv_generados/dwh/bimobile/ContadorDB-dwh-bimobile.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-bimobile.out 2>&1
./comparar.py /oracle/csv_generados/dwh/kdd/ContadorDB-dwh-kdd.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-kdd.out 2>&1
./comparar.py /oracle/csv_generados/dwh/staging/ContadorDB-dwh-staging.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-staging.out 2>&1
./comparar.py /oracle/csv_generados/dwh/mapas/ContadorDB-dwh-mapas.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-mapas.out 2>&1
./comparar.py /oracle/csv_generados/dwh/dwh/ContadorDB-dwh-dwh.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-dwh.out 2>&1
./comparar.py /oracle/csv_generados/dwh/kdd_staging/ContadorDB-dwh-kdd_staging.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-kdd_staging.out 2>&1
./comparar.py /oracle/csv_generados/dwh/segmentador/ContadorDB-dwh-segmentador.out	/home/oracle11/contador_archivos_csv/contador-archivos-dwh-segmentador.out 2>&1
./comparar.py /oracle/csv_generados/kml/camaleon/ContadorDB-kml-camaleon.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-camaleon.out 2>&1
./comparar.py /oracle/csv_generados/kml/dwh/ContadorDB-kml-dwh.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-dwh.out 2>&1
./comparar.py /oracle/csv_generados/kml/migra/ContadorDB-kml-migra.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-migra.out 2>&1
./comparar.py /oracle/csv_generados/kml/traspaso/ContadorDB-kml-traspaso.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-traspaso.out 2>&1
./comparar.py /oracle/csv_generados/kml/falcon/ContadorDB-kml-falcon.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-falcon.out 2>&1
./comparar.py /oracle/csv_generados/kml/reportes/ContadorDB-kml-reportes.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-reportes.out 2>&1
./comparar.py /oracle/csv_generados/kml/dbreglas2/ContadorDB-kml-dbreglas2.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-dbreglas2.out 2>&1
./comparar.py /oracle/csv_generados/kml/factura/ContadorDB-kml-factura.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-factura.out 2>&1 
./comparar.py /oracle/csv_generados/kml/dbreglas/ContadorDB-kml-dbreglas.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-dbreglas.out 2>&1
./comparar.py /oracle/csv_generados/kml/dbadmin/ContadorDB-kml-dbadmin.out	/home/oracle11/contador_archivos_csv/contador-archivos-kml-dbadmin.out 2>&1
./comparar.py /oracle/csv_generados/kmlhis/traspaso/ContadorDB-kmlhis-traspaso.out	/home/oracle11/contador_archivos_csv/contador-archivos-kmlhis-traspaso.out 2>&1
./comparar.py /oracle/csv_generados/kmlhis/cpp/ContadorDB-kmlhis-cpp.out	/home/oracle11/contador_archivos_csv/contador-archivos-kmlhis-cpp.out 2>&1
./comparar.py /oracle/csv_generados/kmlhis/reportes/ContadorDB-kmlhis-reportes.out	/home/oracle11/contador_archivos_csv/contador-archivos-kmlhis-reportes.out 2>&1
./comparar.py /oracle/csv_generados/kmlhis/dbadmin/ContadorDB-kmlhis-dbadmin.out	/home/oracle11/contador_archivos_csv/contador-archivos-kmlhis-dbadmin.out 2>&1
./comparar.py /oracle/csv_generados/repgi/edata/ContadorDB-repgi-edata.out	/home/oracle11/contador_archivos_csv/contador-archivos-repgi-edata.out 2>&1
./comparar.py /oracle/csv_generados/repgi/staging/ContadorDB-repgi-staging.out	/home/oracle11/contador_archivos_csv/contador-archivos-repgi-staging.out 2>&1
./comparar.py /oracle/csv_generados/repgi/mstr_oracle/ContadorDB-repgi-mstr_oracle.out	/home/oracle11/contador_archivos_csv/contador-archivos-repgi-mstr_oracle.out 2>&1
./comparar.py /oracle/csv_generados/repgi/ods/ContadorDB-repgi-ods.out	/home/oracle11/contador_archivos_csv/contador-archivos-repgi-ods.out 2>&1
./comparar.py /oracle/csv_generados/repgi/repgi/ContadorDB-repgi-repgi.out	/home/oracle11/contador_archivos_csv/contador-archivos-repgi-repgi.out 2>&1 